build and install gcc to $prefix, then run:
LD_LIBRARY_PATH=$prefix/lib64 CXX=$prefix/bin/g++ make run

this test has a custom handle_contract_violation that throws an exception
this test is built with -fcontract-continuation-mode=on

since 1) our fun() is not marked noexcept and 2) the continue mode is set to
on, we expect the exception thrown within the contract violation handler to
propagate back up into the catch block located in main()

expected output therefore ends in:
	synth caught indirect: -1

